name: Static Analysis
on: workflow_dispatch

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Zip production files
        run: yarn run src:zip

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          appname: 'Minima APK + MiniDAPPS'
          version: Filez v${{ steps.package-version.outputs.current-version}} - Github
          createprofile: false
          filepath: 'maximize-src-${{ steps.package-version.outputs.current-version}}.mds.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
